In [24]:
#Importing dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from neighbors.models import KNeighborsClassifier,KNeigborsRegressor
from sklearn.datasets import load_iris,load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error,confusion_matrix

import warnings
warnings.filterwarnings('ignore')

### KNeighborsClassifier

In [8]:
#Importing classification data
X,y = load_iris(return_X_y= True,as_frame= True)
X.shape,y.shape

((150, 4), (150,))

In [4]:
#Dividing into train-test set
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,shuffle= True,random_state= 42)
X_train.shape,X_test.shape

((120, 4), (30, 4))

In [9]:
#Running the model
clf = KNeighborsClassifier(k=3)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [17]:
#Confusion matrix
print("Confusion Mtrix:")
print(confusion_matrix(y_test,y_pred))

#Accuracy
acc = np.sum(y_pred == y_test.to_numpy()) / len(y_test)
print(f"Accuracy is {acc*100}%")

Confusion Mtrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy is 100.0%


### KNeighborsRegressor

In [21]:
#Load dataset
X,y = load_boston(return_X_y= True)
X.shape,y.shape

((506, 13), (506,))

In [22]:
#Train-Test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,shuffle= True,random_state= 42)
X_train.shape,X_test.shape

((404, 13), (102, 13))

In [25]:
#Scaling the data
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [26]:
#Running the models
clf = KNeigborsRegressor(k=11)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [27]:
#RMSE error
print("RMSE error: {}".format(mean_squared_error(y_pred,y_test)))

RMSE error: 24.68932020742181
